
-- No. Historia: icm-001-database
-- Comment: First DDL version
CREATE TABLE ICM.CLIENT (
	ID_CLIENT BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	NAME VARCHAR(300) NOT NULL,
    ADDRESS VARCHAR(600) NOT NULL,
	CONSTRAINT CLIENT_PK PRIMARY KEY (ID_CLIENT)
);